sudo: false
language: erlang
otp_release:
  - 22.3
  - 23.3
  - 24.1
before_install:
  - ./ci before_install "${PWD:?}"/rebar3
  - pip install --user codecov
install:
  - ./ci install "${PWD:?}"/rebar3
script:
  - ./ci script "${PWD:?}"/rebar3
cache:
  directories:
    - .plt
after_success:
  - codecov
