name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  ubuntu:
    name: "Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.3, 23.3, 24.1]
      fail-fast: false
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v2
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Tests
      run: rebar3 ct
    - name: prepare coverage report
      run: rebar3 codecov analyze --lcov --json false
    - name: report coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: small_tests on OTP ${{matrix.otp}}
        path-to-lcov: ./lcov.info

  coveralls:
    needs: [ubuntu]
    runs-on: ubuntu-latest
    steps:
      - name: Finish coveralls parallel build
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
